Updating pull-request and main deploy

diff --git a/.github/workflows/reusable-queue-management-frontend-cypress.yaml b/.github/workflows/reusable-queue-management-frontend-cypress.yaml
--- a/.github/workflows/reusable-queue-management-frontend-cypress.yaml
+++ b/.github/workflows/reusable-queue-management-frontend-cypress.yaml
@@ -30,20 +30,41 @@ jobs:
         with:
           ref: ${{ inputs.ref }}
 
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20.11.1' 
+
       - name: Configuration Files
         run: |
           
-          mkdir -p frontend/public/config/kc
+          mkdir -p frontend/public/static/keycloak
+          mkdir -p frontend/public/config
+          echo "Checking directory existence..."
+          if [ -d "frontend/public/config/" ]; then 
+            echo "Directory exists."
+          else
+            echo "Error: Directory does not exist."
+            exit 1
+          fi
 
           cat << EOF > frontend/public/config/configuration.json
           {
-            "FEEDBACK_ENABLED": true,
-            "KEYCLOAK_CONFIG_URL": "./public/config/kc/keycloak-public.json",
-            "VUE_APP_FOOTER_LINKS": "https://www.icbc.com/locators",
-            "VUE_APP_FOOTER_MSG": "Looking for ICBC Services? Ensure you are at the right place by visiting {link} icbc.com/locators",
-            "VUE_APP_HEADER_LINKS": "https://www.gov.bc.ca/bcservicescardapp{link}https://www.bceid.ca",
-            "VUE_APP_HEADER_MSG": "Before you start – do you have the {link}BC Services Card app{link} or {link}Basic BCeID{link}? Login needed to confirm appointment.",
-            "VUE_APP_ROOT_API": "http://localhost:5000/api/v1"
+            "VUE_APP_API_URL": "http://localhost:5000/api/v1",
+            "VUE_APP_SOCKET_URL" : "http://localhost:5000",
+            "BPM_URL": "https://dev-sbc-ffa-bpm.apps.silver.devops.gov.bc.ca/camunda",
+            "FORM_IO_USER_ROLES": "formsflow-reviewer",
+            "FORM_IO_API_URL": "https://dev-sbc-ffa-forms.apps.silver.devops.gov.bc.ca",
+            "FORM_IO_RESOURCE_ID": "6078c70bdb2a9c357e91ba44",
+            "FORM_IO_REVIEWER_ID": "6078c79cdb2a9c5ce791ba51",
+            "FORM_IO_REVIEWER": "formsflow-reviewer",
+            "FORM_FLOW_API_URL" : "https://dev-sbc-ffa-api.apps.silver.devops.gov.bc.ca",
+            "FORM_FLOW_URL" : "https://dev-sbc-serviceflow.apps.silver.devops.gov.bc.ca",
+            "SERVICEFLOW_ENABLED": false,
+            "WEBSOCKET_ENCRYPT_KEY": "123455",
+            "SOCKET_TIMEOUT": 30000,
+            "SOCKET_DELAY_MAX" : 3000,
+            "FORMIO_JWT_SECRET": "12345"
           }
           EOF
 
@@ -58,16 +79,18 @@ jobs:
           }
           EOF
 
-          cat << EOF > frontend/cypress.env.json
-          {
-            "BCEID_ENDPOINT": "${{ vars.BCEID_ENDPOINT_DEV}}",
-            "BCEID_PASSWORD": "${{ secrets.bceid-password }}",
-            "BCEID_USERNAME": "${{ vars.CYPRESS_BCEID_USERNAME }}"
-          }
-          EOF
+      - name: Load Configuration JSON
+        id: load_config
+        run: |
+          echo "Loading environment variables from configuration.json"
+          # Extract variables from configuration.json and export them
+          export $(jq -r 'to_entries | .[] | "\(.key)=\(.value)"' frontend/public/config/configuration.json)
+          # Save variables to $GITHUB_ENV
+          echo "VUE_APP_API_URL=${VUE_APP_API_URL}" >> $GITHUB_ENV
+          echo "VUE_APP_SOCKET_URL=${VUE_APP_SOCKET_URL}" >> $GITHUB_ENV
 
       - name: Cypress Run
-        uses: cypress-io/github-action@v6.0.0
+        uses: cypress-io/github-action@v2
         env:
           CYPRESS_PROJECT_ID: ${{ secrets.cypress-project-id }}
           CYPRESS_RECORD_KEY: ${{ secrets.cypress-record-key }}
